apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: release
      taskSpec:
        stepTemplate:
          name: ""
          env:
          - name: PROMOTION_ENVIRONMENTS
            value: "integration"
        steps:
        - image: uses:lighthouse:devops/jx3-pipeline-catalog-keyfactor/tasks/docker-helm/release.yaml@main
          name: ""
  serviceAccountName: tekton-bot
  timeout: 1h
